### ISSUE TITLE
Unable to generate contracts

### ISSUE THREAD

**Issue by tim-white87** [mwerle/OrbitalMaterialScience#11]
Hey Mwerle,

Much thanks for this, it is an awesome addition. Basically with the latest version, I am unable to generate new contracts (and none get auto generated). I confirmed it was the release by downloading https://github.com/mwerle/OrbitalMaterialScience/releases/tag/0.7a0-mw7-KSP120_pre and then generating a new contract via the cheat window. In the earlier version, I was able to generate contracts, however the latest no longer able to create them. Note, I had to roll back to 1.2.2 in KSP for this to work as well, it doesn't appear compatible with 1.3 yet. I am downloading the code to see if I can fix the issue on my own. If you are aware of a quick fix, please let me know and I will hold off on trying to fix it.

Thanks!
Tim

**Comment by tim-white87** [comment]
It looks like its likely this: https://github.com/mwerle/OrbitalMaterialScience/commit/b391eb59a3dd021ebb313a6439a13b9a3f33dd13

**Comment by mwerle** [comment]
Hi Tim,

Thanks I'm partway through updating for 1.3 - fixing GUI click-through etc. 

I'll take a look at why contracts aren't working. 

Unfortunately don't  have much time but will try to make a point release soon.

**Comment by mwerle** [comment]
Contract generation had changed somewhat in 1.3; fixed in f60b2b78956dec38dd46b260aba427839ff27aa3

**Comment by mwerle** [comment]
Hopefully fixed in [0.7a0-mw8](https://github.com/mwerle/OrbitalMaterialScience/releases/tag/0.7a0-mw8).

**Comment by tim-white87** [comment]
Thanks for the quick fix, I will update KSP and give it a shot this evening.
