### ISSUE TITLE
KEES Contract: experiment recovery is not always triggered 

### ISSUE THREAD

**Issue by mwerle** [mwerle/OrbitalMaterialScience#13]
Contracts only complete when an experiment is recovered in a KEES PEC.

**Comment by mwerle** [comment]
Should be fixed in release 0.7a0-mw9

**Comment by Gordon-Dry** [comment]
I also had this, on two experiments.
The results were properly transferred to the vessel's hard drive, but on vessel recovery the contracts were not fulfilled.
I assume that I do not have to detach the KEES parts and bring them back ...?

**Comment by mwerle** [comment]
You do have to return the KEES experiment part itself.  KEES works differently to "standard" experiments in that you have to return the part, not just the data.

**Comment by Gordon-Dry** [comment]
Ok. This info was missing somewhere ...
Could be written into the contract description.

**Comment by Gordon-Dry** [comment]
Hmm, well...

This time I detached all parts after finalizing the experiments (what is only possible from vessel focus) and put them back into the pod's inventory, but the contract weren't fulfilled neither ...

**Comment by mwerle** [comment]
Ok, I'll need to investigate.
Can you attach a logfile of a gaming session where this occurred please?

I'll also see about adding it to the description of the contract although the KSPedia also details how to run KEES experiments.

**Comment by Gordon-Dry** [comment]
Logs:
https://www.dropbox.com/s/bhrz3bhiyrcd9nd/2018-10-09_1%20KSP.log%20and%20stuff.7z?dl=1

At the end of that session I had a huge exception spam about planting a flag ...
https://forum.kerbalspaceprogram.com/index.php?/topic/178829-plant-flag-on-earth-explosion-sound-no-controls-log-spam/

**Comment by mwerle** [comment]
Thanks Gordon-Dry,

So you have a gazillion mods in there. While I'm not aware of any specific incompatibilities, "Stage Recovery" and "Science Full Reward" are potential red flags. 

Having said that, the log file seems to show that the contract was completed successfully (KSP.log, line 297294).

As I can't see anything obvious in the log file I'm afraid I really can't investigate such a heavily modded install further. It "works for me" and I haven't had any other reports of it not working recently so all I can suggest at the moment is that you try to disable some of your mods and try to isolate which mod is causing the issue. If you do manage to find the offending mod I (and/or the other mod author) can try to fix the incompatibility.

Sorry. And thank you very much for such a comprehensive log archive!

**Comment by Gordon-Dry** [comment]
I will it remove again, because I just discovered that my save (and all backups since Oct 6th) are borked, there are NaN over the place in the persistent file ...
No offending, but that was the time I added this mod to the career.

I want to untidy my mod folder and start again.

And the fact that going EVA in space is slow and sluggish as soon as any KEES part is involved (carrying or not, it's enough to have one part attached to the vessel) makes me wonder if this mod has serious issues.

Fun fact is, the fps are okay and the physics delta is okay, but the movement is slow and sluggish whatsoever.
It's like without KEES the EVA movability is 10x better.

**Comment by mwerle** [comment]
I'm sorry to hear that. I've played all my saves with NEOS from way back when N3h3mia was developing it and never encountered any major issues (unless playing and debugging a development version).

No idea why KEES would cause slowdowns during EVA - it's just leveraging KIS and there shouldn't be any processing happening during EVA. I'll take a look but I strongly suspect some interaction between your mods. Likely to be triggered by adding KEES on top of your existing install, but I'm somewhat confident KEES on it's own does not have any major issues.

**Comment by mwerle** [comment]
Cannot repro, and can't see any major performance impact with KEES during IVA either using a profiler.

I'm very sorry, but unless you can get a repro case with a minimal number of other mods going, I'll have to chalk this up to being due to mod conflicts.
