### ISSUE TITLE
[x] Science Mod bypasses experiment wait times

### ISSUE THREAD

**Issue by mwerle** [mwerle/OrbitalMaterialScience#20]
Reported by DrPastah on the KSP Form.

https://forum.kerbalspaceprogram.com/index.php?/topic/149298-131-nehemia-engineering-orbital-science-neos-07b3/&do=findComment&comment=3229021

**Comment by mwerle** [comment]
Confirmed; also leaves the experiment in whatever state it was in (started/running/...).

[X] Science calls "DeployExperiment" on the experiment. It does some special handling for the DMagic 
 experiments; perhaps it could also do some special handling for ours.

**Comment by linuxgurugamer** [comment]
There is a config file in [x] Science which can be used to tell it to ignore certain experiments.  The file is called "science.cfg", and you can update it using MM

**Comment by mwerle** [comment]
Note to self: 
https://github.com/thewebbooth/KSP-X-Science/blob/master/X-Science/GameData/%5Bx%5D%20Science!/science.cfg

Considering the precedent, probably best to submit a pull-request to x-science maintainer instead of adding an MM patch into NEOS.

**Comment by linuxgurugamer** [comment]
I would suggest that given the lack of updates by the maintainer, that you provide a MM script to udpate the file

**Comment by mwerle** [comment]
Thanks.

I've just sent a [pull request](https://github.com/thewebbooth/KSP-X-Science/pull/24) to @thewebbooth but will add MM patches if he hasn't integrated it by the time I'm ready for my next release.

Leaving this open to track.

**Comment by mwerle** [comment]
This appears to have been committed to X-Science
in commit thewebbooth/KSP-X-Science@10f7a2de

Not sure why @thewebbooth didn't just merge the pull request... well, each author to their own.
