### ISSUE TITLE
KAC alarm is too early for KEES experiments

### ISSUE THREAD

**Issue by Gordon-Dry** [mwerle/OrbitalMaterialScience#28]
When the exposure time of these experiments is at ~ 60% the KAC alarm is set.

**Comment by mwerle** [comment]
Hi Gordon,

I can't reproduce this. Could you please provide steps to reproduce?  Eg, did you pause the game while the experiment was running, did you halt the exposure time resource, anything else relevant you can think of?

Thanks.

**Comment by Gordon-Dry** [comment]
I just did normal stuff - continueing orbiting.
A slow timewarp.

**Comment by mwerle** [comment]
Hi Gordon,
I'm afraid I still can't repro this issue, it all works perfectly for me, now on latest KSP (1.6.1), KAC 3.10.0.0, and the last release of NEOS (0.8.0). I tested every KEES experiment at Warp 4 (the fastest possible in LKO).

Can you please provide more information? Log files for a start and ideally a savegame able to reproduce this.

**Comment by mwerle** [comment]
Cannot repro and user has not provided additional information.

Please re-open if this is still an issue.
