### ISSUE TITLE
MEP experiments do not work

### ISSUE THREAD

**Issue by sokol290769** [mwerle/OrbitalMaterialScience#35]
When you install MEE1 or MEE2 experiments in the MEP-825 lab, you can run Experiment preparing from the context menu. After that, lab time 1.0 will be displayed. Then nothing happens, the experiment does not continue and nothing can be done with it. In version 1.3.0 of the game after the expiration of the Experiment preparing time, the context menu provided an opportunity to select Experiment starting, after which an animated image of the installation on the tablet platform with samples was launched and the lab time of the experiment itself was displayed (for example, for MEE-1 it is 20). After this time, the experiment could be completed and moved to the container for finalization and return to Kerbin. This is not happening now. Mod version 0.8.0, game version 1.5.1. Tested with both mods and clean install. Other laboratories (MPL-600 and MSL-1000) work fine.

**Comment by sokol290769** [comment]
> When you install ME1 or ME2 experiments in the MAR-825 lab, you can run Experiment preparing from the context menu. After that, lab time 1.0 will be displayed. Then nothing happens, the experiment does not continue and nothing can be done with it. In version 1.3.0 of the game after the expiration of the Experiment preparing time, the context menu provided an opportunity to select Experiment starting, after which an animated image of the installation on the tablet platform with samples was launched and the lab time of the experiment itself was displayed (for example, for MEE-1 it is 20). After this time, the experiment could be completed and moved to the container for finalization and return to Kerbin. This is not happening now. Mod version 0.8.0, game version 1.5.1. Tested with both mods and clean install Other laboratories (PL-600 and MSL-1000 work fine).

**Comment by sokol290769** [comment]
In General the problem in me, not in this mod. You need to carefully read what is given in the description of each experiment. In short, for the normal operation of the MEP-825 laboratory, the orbital station must include one of the two laboratories: MPL-100 - or MSL-600. And also at least one scientist in them. Then everything works as it should.

**Comment by mwerle** [comment]
Sorry for the slow response; thanks for the update.
