### ISSUE TITLE
KEMINI - ensure adding/removing experiments from capsule affects weight

### ISSUE THREAD

**Issue by mwerle** [mwerle/OrbitalMaterialScience#6]
Experiments have a weight configured, but adding/removing experiments does not change the weight of the capsule.

**Comment by Kerbas-ad-astra** [comment]
I believe the [IPartMassModifier](https://kerbalspaceprogram.com/api/interface_i_part_mass_modifier.html) interface is what you want.

**Comment by mwerle** [comment]
THANKS!  All done in mw_dev branch.

EDIT: including for OMS

**Comment by mwerle** [comment]
For future reference: http://forum.kerbalspaceprogram.com/index.php?/topic/137059-changes-to-ipartmassmodifier-ipartcostmodifier-and-ipartsizemodifier-in-build-1209/
